In [16]:
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np
import sys
import time

### 读取数据

In [17]:
def load_dataset(dataSet, batch_size=64):
    if sys.platform.startswith('win'):
        num_workers = 0  # 0表示不用额外的进程来加速读取数据
    else:
        num_workers = 4
        print('linux')
    dataset_iter = torch.utils.data.DataLoader(dataSet, batch_size=batch_size, shuffle=True, num_workers=num_workers)
    return dataset_iter

### 实现softmax运算

In [21]:
def softmax(X):
    x_exp = X.exp()
    sum = x_exp.sum(dim=1, keepdim=True)
    return x_exp / sum

### 定义模型

In [60]:
def model(data, w, b):
    return softmax(torch.mm(data.view(-1, 784), w) + b)

### 定义损失函数

In [157]:
def loss(lable, y):
    # print(lable.view(-1, 1))
    return - torch.log(y.gather(1, lable.view(-1, 1)))

### 定义优化算法

In [158]:
def sgd(params, lr, batch_size): 
    for param in params:
        param.data -= lr * param.grad / batch_size # 注意这里更改param时用的param.data

### 计算准确率

In [159]:
def accuracy(lable, y):
    return (y.argmax(dim=1) == y).float.mean().item()

### 评价准确率

In [160]:
def evaluate_accuracy(data_iter, parmas):
    acc_sum, n = 0.0, 0
    w, b = params
    for X, y in data_iter:
        acc_sum += (model(X, w, b).argmax(dim=1) == y).float().sum().item()
        n += y.shape[0]
    return acc_sum / n

### 训练模型

In [161]:
def training_loop(net, loss, n_epochs, params, train_dataset, test_dataset, batch_size=64, lr=0.001,):
    train_iter = load_dataset(train_dataset, batch_size)
    test_iter = load_dataset(test_dataset, batch_size)
    for epoch in range(n_epochs+1):
        train_loss_sum, train_acc_sum, n = 0.0, 0.0, 0
        for x, lable in train_iter:
            n += lable.shape[0]
            w, b = params
            y = net(x, w, b)
            l = loss(lable, y).sum()
            if params[0].grad is not None:
                for param in params:
                    param.grad.data.zero_()  # 梯度清零
            l.backward()
            sgd(params, lr, batch_size)
            train_loss_sum += l.item()
            train_acc_sum += (y.argmax(dim=1) == lable).sum().item()
        test_acc = evaluate_accuracy(test_iter, params)
        print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f,  train acc2_: %.3f,'
              % (epoch + 1, train_loss_sum / n, train_acc_sum / n, test_acc, evaluate_accuracy(train)))

In [162]:
if __name__ == '__main__':
    savePath = './Fashion-MNIST/'
    mnist_train = torchvision.datasets.FashionMNIST(root=savePath, train=True, download=True, transform=transforms.ToTensor())
    mnist_test = torchvision.datasets.FashionMNIST(root=savePath, train=False, download=True, transform=transforms.ToTensor())
    
    # 初始化模型参数
    num_inputs = 784
    num_outputs = 10
    w = torch.tensor(np.random.normal(0, 0.1, (num_inputs, num_outputs)), dtype=torch.float)
    b = torch.zeros(num_outputs, dtype=torch.float)
    w.requires_grad_(requires_grad=True)
    b.requires_grad_(requires_grad=True) 
    print(b.shape)
    
    n_epochs=1
    params = [w, b]
    lr = 0.001
    training_loop(net=model, loss=loss, n_epochs=n_epochs, batch_size=64, params=params, 
                  lr=0.001,train_dataset=mnist_train, test_dataset=mnist_test)

torch.Size([10])
linux
linux
tensor([[1.1479],
        [3.4923],
        [2.7604],
        [6.2296],
        [1.1171],
        [1.1789],
        [1.8271],
        [2.4174],
        [3.4046],
        [4.2936],
        [2.6558],
        [0.6352],
        [1.8937],
        [2.0271],
        [3.7170],
        [2.7519],
        [2.7019],
        [3.8432],
        [2.6398],
        [2.1262],
        [2.9771],
        [3.1874],
        [1.5085],
        [1.7312],
        [1.8672],
        [2.4381],
        [1.8760],
        [2.8743],
        [2.9577],
        [1.8012],
        [6.5234],
        [1.1647],
        [2.6920],
        [2.1385],
        [1.3151],
        [3.2109],
        [1.6675],
        [1.7330],
        [2.9513],
        [2.0621],
        [2.2862],
        [4.1587],
        [0.8628],
        [3.9929],
        [4.0776],
        [3.1462],
        [3.2456],
        [2.7446],
        [3.4926],
        [2.9272],
        [3.6234],
        [3.4317],
        [2.4454],
        [5.4330],

tensor([[3.0342],
        [1.6417],
        [2.1953],
        [0.7410],
        [1.4490],
        [3.0819],
        [2.0468],
        [3.2867],
        [1.0993],
        [3.4004],
        [2.7134],
        [1.7543],
        [3.3717],
        [2.7626],
        [1.4492],
        [2.8181],
        [2.7785],
        [1.6664],
        [2.5346],
        [3.1903],
        [5.4821],
        [1.9740],
        [3.1305],
        [3.3483],
        [3.1165],
        [4.4653],
        [1.9831],
        [2.6234],
        [1.7813],
        [1.6540],
        [2.8464],
        [3.2928],
        [1.1073],
        [1.9879],
        [1.2221],
        [3.8581],
        [3.2880],
        [1.8977],
        [1.4804],
        [3.1760],
        [2.2849],
        [3.3771],
        [3.5995],
        [1.7475],
        [2.2551],
        [3.1927],
        [4.4238],
        [3.3768],
        [2.9157],
        [2.6953],
        [2.9575],
        [2.6044],
        [2.5257],
        [2.4207],
        [1.2160],
        [2

        [2.8066]], grad_fn=<NegBackward>)
tensor([[1.5168],
        [1.7977],
        [1.8321],
        [3.0632],
        [1.5687],
        [1.9352],
        [2.5429],
        [1.4764],
        [1.1411],
        [2.2393],
        [2.1313],
        [1.8840],
        [2.6070],
        [3.7609],
        [1.8225],
        [2.1222],
        [1.5682],
        [4.6063],
        [2.2073],
        [5.6506],
        [1.4268],
        [2.3812],
        [2.2273],
        [2.7916],
        [1.8740],
        [3.7645],
        [2.6804],
        [2.7117],
        [1.5096],
        [2.5577],
        [2.6924],
        [1.4737],
        [3.6095],
        [3.6387],
        [1.8228],
        [2.3452],
        [1.3874],
        [2.4762],
        [2.0622],
        [2.2925],
        [3.0786],
        [4.2148],
        [1.2928],
        [1.7084],
        [1.9234],
        [2.5935],
        [1.8001],
        [2.0712],
        [2.1050],
        [2.3123],
        [2.8360],
        [1.3492],
        [1.3848],
    

tensor([[1.6202],
        [1.9053],
        [2.2232],
        [2.3578],
        [0.8646],
        [2.0287],
        [2.7666],
        [2.2723],
        [0.8234],
        [1.8441],
        [2.6317],
        [1.6862],
        [1.5535],
        [5.3423],
        [2.1072],
        [1.8489],
        [1.5147],
        [2.2276],
        [1.3682],
        [2.0017],
        [2.9498],
        [2.2829],
        [1.1600],
        [1.8060],
        [1.7448],
        [4.0878],
        [1.8762],
        [1.5825],
        [2.0183],
        [2.1089],
        [2.5636],
        [0.8500],
        [1.8046],
        [2.0561],
        [1.9530],
        [1.9125],
        [5.5325],
        [2.5136],
        [2.5789],
        [1.4197],
        [3.6517],
        [2.3041],
        [1.0948],
        [2.3509],
        [3.7168],
        [1.9660],
        [5.5735],
        [3.4703],
        [3.4499],
        [0.5923],
        [2.3819],
        [2.4613],
        [2.1013],
        [1.7465],
        [2.4174],
        [2

tensor([[2.4490],
        [2.4179],
        [2.1136],
        [2.5819],
        [2.5607],
        [2.1479],
        [1.3591],
        [1.9953],
        [5.2454],
        [3.6887],
        [2.2328],
        [2.7038],
        [1.1648],
        [4.1436],
        [0.7031],
        [1.4013],
        [5.2502],
        [4.1681],
        [2.6332],
        [2.4314],
        [1.9930],
        [1.2696],
        [2.4102],
        [2.3673],
        [5.8442],
        [2.2623],
        [4.9008],
        [3.2156],
        [2.4762],
        [2.6244],
        [3.0319],
        [1.7522],
        [2.5578],
        [4.6933],
        [3.4086],
        [1.9488],
        [2.0807],
        [1.9592],
        [1.7171],
        [1.8658],
        [2.3431],
        [2.0370],
        [2.1312],
        [2.3271],
        [5.5294],
        [1.4072],
        [1.9612],
        [2.2949],
        [2.8168],
        [2.3333],
        [0.9816],
        [2.6787],
        [0.7786],
        [1.5961],
        [1.4881],
        [2

tensor([[1.7382],
        [3.5605],
        [1.1052],
        [0.7099],
        [3.0204],
        [1.1566],
        [1.6312],
        [0.8226],
        [2.7798],
        [1.7422],
        [1.4287],
        [2.1892],
        [1.0358],
        [2.9519],
        [2.3299],
        [2.3028],
        [2.0739],
        [1.7883],
        [2.6698],
        [1.7625],
        [2.6090],
        [1.5368],
        [1.6675],
        [2.3583],
        [2.4191],
        [2.2146],
        [2.5142],
        [3.6085],
        [1.6666],
        [2.9119],
        [1.5558],
        [2.0649],
        [3.0071],
        [1.7475],
        [2.0227],
        [1.9846],
        [1.3137],
        [2.9128],
        [3.1334],
        [3.8547],
        [2.4377],
        [1.9348],
        [2.6903],
        [1.7465],
        [1.9690],
        [2.5237],
        [3.1323],
        [1.9037],
        [1.6605],
        [1.9976],
        [2.2820],
        [3.6672],
        [2.9058],
        [2.2955],
        [2.5157],
        [1

tensor([[2.6011],
        [1.3019],
        [2.3040],
        [2.7610],
        [1.9524],
        [1.3880],
        [1.6233],
        [1.5743],
        [1.8768],
        [1.4990],
        [3.3550],
        [2.4275],
        [2.0903],
        [2.0525],
        [1.5651],
        [3.2281],
        [2.1072],
        [2.0143],
        [2.1667],
        [3.7677],
        [2.3913],
        [3.2295],
        [1.5438],
        [1.8758],
        [1.9241],
        [3.4834],
        [1.8309],
        [3.1296],
        [1.8890],
        [2.1312],
        [2.7158],
        [2.2771],
        [1.9331],
        [1.4875],
        [1.6599],
        [2.6433],
        [1.3568],
        [3.7665],
        [3.5118],
        [2.0166],
        [1.8403],
        [1.4588],
        [1.8903],
        [2.3244],
        [3.3785],
        [2.6974],
        [2.9834],
        [1.9716],
        [1.7932],
        [3.2958],
        [3.0350],
        [2.0116],
        [4.0881],
        [2.4184],
        [1.9392],
        [2

tensor([[1.2255],
        [1.9852],
        [1.1523],
        [2.6546],
        [2.3230],
        [1.9846],
        [1.4361],
        [2.1896],
        [2.2640],
        [2.4239],
        [2.6897],
        [0.5916],
        [1.7056],
        [0.9168],
        [2.3162],
        [2.1916],
        [1.7663],
        [1.5453],
        [4.3089],
        [2.8692],
        [2.2520],
        [1.5098],
        [2.1937],
        [1.4243],
        [2.1969],
        [2.2765],
        [3.8412],
        [2.5631],
        [2.5878],
        [3.1996],
        [1.9722],
        [2.2505],
        [3.0468],
        [1.8590],
        [2.2377],
        [1.8697],
        [2.3520],
        [2.4545],
        [2.0673],
        [1.8132],
        [2.5391],
        [2.7358],
        [2.0679],
        [1.6639],
        [2.4861],
        [2.6425],
        [1.6836],
        [2.3157],
        [2.3389],
        [1.8748],
        [2.3516],
        [2.5857],
        [1.7648],
        [2.3466],
        [2.2890],
        [2

tensor([[2.3077],
        [1.1932],
        [0.8833],
        [1.7691],
        [2.3188],
        [1.6961],
        [1.7144],
        [2.1167],
        [2.2056],
        [1.2499],
        [1.3127],
        [1.7156],
        [1.6159],
        [2.2051],
        [1.1671],
        [2.1918],
        [3.6648],
        [1.5275],
        [1.9992],
        [2.3052],
        [1.9726],
        [2.7458],
        [1.4480],
        [2.6833],
        [1.3184],
        [2.4679],
        [1.6991],
        [1.9403],
        [2.5705],
        [2.0055],
        [1.8143],
        [2.1104],
        [1.7029],
        [2.6854],
        [2.2062],
        [2.8314],
        [2.9898],
        [1.8525],
        [2.4091],
        [3.5747],
        [2.4955],
        [1.8324],
        [3.1563],
        [1.6650],
        [2.8168],
        [2.3521],
        [1.3832],
        [2.1360],
        [1.7751],
        [2.3347],
        [2.1339],
        [4.4003],
        [3.2324],
        [4.1815],
        [2.2906],
        [2

tensor([[2.2420],
        [1.8360],
        [2.1595],
        [1.3067],
        [2.4681],
        [4.6809],
        [1.3253],
        [1.4345],
        [1.7666],
        [1.4718],
        [2.7448],
        [2.0460],
        [1.4827],
        [1.9967],
        [1.1225],
        [3.3036],
        [2.5058],
        [2.6438],
        [1.8293],
        [1.9240],
        [1.6679],
        [2.1256],
        [1.8738],
        [1.4831],
        [3.6930],
        [2.5627],
        [1.9469],
        [2.4147],
        [2.3156],
        [3.3294],
        [3.0191],
        [3.1098],
        [1.4685],
        [2.3681],
        [1.0250],
        [1.4000],
        [5.4433],
        [1.6049],
        [1.8390],
        [2.0653],
        [2.0726],
        [1.5908],
        [2.1223],
        [2.0176],
        [1.6856],
        [1.5653],
        [2.1220],
        [2.1825],
        [1.8917],
        [3.5168],
        [2.2386],
        [2.5934],
        [2.3483],
        [4.0129],
        [1.1511],
        [2

tensor([[2.8983],
        [2.2921],
        [2.7409],
        [1.0981],
        [2.3886],
        [4.0405],
        [1.8127],
        [2.6268],
        [2.7668],
        [1.4686],
        [1.3533],
        [1.3959],
        [1.9514],
        [1.9893],
        [2.9576],
        [2.6059],
        [2.4038],
        [2.2806],
        [1.5447],
        [2.1521],
        [2.7258],
        [1.8472],
        [1.6335],
        [1.5477],
        [2.2513],
        [2.0395],
        [3.1898],
        [1.8224],
        [1.9109],
        [2.1670],
        [2.2933],
        [1.3342],
        [2.8088],
        [1.4371],
        [2.4709],
        [2.1058],
        [2.2544],
        [1.7789],
        [2.9403],
        [2.7398],
        [2.4697],
        [2.0703],
        [1.8296],
        [2.3890],
        [1.9414],
        [2.8972],
        [1.0989],
        [2.0288],
        [1.7480],
        [2.7038],
        [1.9561],
        [2.9980],
        [2.2928],
        [3.6575],
        [3.6480],
        [1

tensor([[1.1928],
        [1.8326],
        [1.4731],
        [1.7679],
        [2.1045],
        [1.8895],
        [1.6959],
        [2.5015],
        [2.0054],
        [2.2330],
        [1.8803],
        [2.0457],
        [1.6826],
        [1.3279],
        [2.7828],
        [1.9724],
        [0.6985],
        [2.0353],
        [3.3695],
        [1.1044],
        [3.6421],
        [1.4008],
        [1.9187],
        [2.8513],
        [2.0293],
        [2.5999],
        [1.8391],
        [2.3731],
        [0.9587],
        [1.9590],
        [2.2375],
        [3.7827],
        [3.0413],
        [1.9652],
        [2.0314],
        [1.1227],
        [2.7864],
        [3.6004],
        [1.7154],
        [1.8885],
        [1.9774],
        [2.6631],
        [2.0094],
        [1.9262],
        [2.8372],
        [2.9953],
        [1.2253],
        [1.8395],
        [1.3348],
        [1.6470],
        [1.2464],
        [2.1486],
        [4.1329],
        [0.6190],
        [2.4350],
        [0

tensor([[1.7403],
        [1.9519],
        [2.0997],
        [2.7970],
        [1.4785],
        [2.0503],
        [1.9973],
        [2.6576],
        [2.2466],
        [1.8931],
        [1.4346],
        [1.6808],
        [2.1430],
        [2.1772],
        [2.3909],
        [2.0370],
        [1.6505],
        [1.1219],
        [1.6699],
        [1.7109],
        [2.0620],
        [2.5604],
        [1.5188],
        [1.8731],
        [2.2517],
        [1.6586],
        [1.6667],
        [1.9630],
        [1.6185],
        [2.8077],
        [2.1656],
        [2.9113],
        [2.1414],
        [1.3253],
        [1.7052],
        [2.4892],
        [2.5274],
        [1.8740],
        [1.5503],
        [2.7005],
        [1.2042],
        [2.6620],
        [0.7930],
        [2.0291],
        [1.9242],
        [2.1717],
        [2.5702],
        [1.6204],
        [1.9044],
        [1.9242],
        [1.1635],
        [1.9631],
        [1.9155],
        [2.6745],
        [1.6548],
        [1

        [2.2192]], grad_fn=<NegBackward>)
tensor([[1.1617],
        [2.1514],
        [2.6911],
        [2.4793],
        [2.1767],
        [2.4096],
        [2.4718],
        [0.8936],
        [1.4610],
        [2.3154],
        [2.7404],
        [2.3766],
        [3.1461],
        [2.1846],
        [2.2026],
        [2.9027],
        [2.3276],
        [2.2001],
        [2.5581],
        [1.6884],
        [2.8728],
        [1.9219],
        [2.0276],
        [1.5836],
        [2.1111],
        [0.9476],
        [1.5978],
        [1.8314],
        [2.1044],
        [2.1460],
        [2.7997],
        [1.0237],
        [2.0025],
        [1.8197],
        [2.1881],
        [2.4666],
        [1.9594],
        [1.7773],
        [3.4972],
        [3.0693],
        [1.2134],
        [1.7547],
        [1.7455],
        [3.6433],
        [2.4390],
        [3.7971],
        [2.5256],
        [1.7742],
        [1.2669],
        [2.5359],
        [2.9897],
        [1.3765],
        [2.0478],
    

tensor([[1.8398],
        [1.7423],
        [1.0903],
        [2.6231],
        [4.2056],
        [1.4620],
        [2.5627],
        [1.1516],
        [2.1462],
        [2.2372],
        [1.7392],
        [2.8002],
        [2.5275],
        [2.3007],
        [3.0446],
        [2.4987],
        [1.7923],
        [1.7370],
        [1.5603],
        [1.8619],
        [1.9841],
        [2.4093],
        [3.9324],
        [2.4236],
        [1.4812],
        [2.2695],
        [1.6568],
        [2.1134],
        [2.4024],
        [2.5902],
        [2.3102],
        [1.8181],
        [2.8545],
        [1.9416],
        [1.8627],
        [3.0953],
        [1.8762],
        [2.6964],
        [2.1848],
        [1.9036],
        [2.0330],
        [1.9176],
        [2.1724],
        [2.4229],
        [2.2373],
        [1.3813],
        [2.3124],
        [1.4850],
        [2.6320],
        [2.3422],
        [1.6326],
        [1.9715],
        [3.1062],
        [1.0355],
        [4.4424],
        [1

tensor([[1.8812],
        [2.4950],
        [1.1832],
        [1.5781],
        [1.8266],
        [3.0871],
        [1.6392],
        [1.5273],
        [3.1636],
        [2.9822],
        [2.1620],
        [1.9202],
        [0.5516],
        [1.4331],
        [0.9111],
        [3.3632],
        [1.7135],
        [2.2412],
        [1.1839],
        [0.8771],
        [2.4529],
        [1.3104],
        [1.7788],
        [1.0638],
        [1.7215],
        [2.5352],
        [3.0686],
        [2.4704],
        [2.0344],
        [0.8423],
        [2.4212],
        [2.6676],
        [1.6129],
        [3.1329],
        [1.4381],
        [2.3831],
        [3.0257],
        [1.8668],
        [2.3001],
        [1.9254],
        [2.1920],
        [2.2831],
        [1.8847],
        [2.1344],
        [1.9300],
        [1.5253],
        [2.6462],
        [2.2087],
        [3.0945],
        [2.6396],
        [2.0172],
        [2.4343],
        [3.0150],
        [1.2091],
        [1.6263],
        [1

tensor([[1.3935],
        [2.1667],
        [1.6562],
        [3.4571],
        [1.8703],
        [2.0390],
        [1.7381],
        [1.7465],
        [1.7049],
        [1.4390],
        [2.7032],
        [1.9498],
        [2.4872],
        [1.3368],
        [2.6819],
        [0.6174],
        [2.1821],
        [2.4691],
        [2.0314],
        [1.4417],
        [2.4390],
        [1.9954],
        [1.7740],
        [2.6398],
        [2.0532],
        [1.9138],
        [1.8273],
        [1.9698],
        [1.7841],
        [2.2872],
        [1.9050],
        [4.1692],
        [1.7278],
        [2.1639],
        [1.3984],
        [1.4945],
        [3.3605],
        [2.9192],
        [0.8697],
        [2.4114],
        [1.7435],
        [1.6660],
        [1.7751],
        [1.5392],
        [1.9190],
        [2.8258],
        [0.9709],
        [2.1303],
        [2.1356],
        [1.3515],
        [0.9325],
        [1.9837],
        [1.9583],
        [1.5590],
        [2.4897],
        [1

tensor([[2.7182],
        [1.1715],
        [2.0562],
        [1.8215],
        [1.8555],
        [1.9944],
        [1.7154],
        [0.8222],
        [2.2666],
        [2.1758],
        [1.7167],
        [0.9034],
        [2.1885],
        [3.4441],
        [2.2014],
        [0.9978],
        [2.5293],
        [1.3359],
        [2.1561],
        [2.3878],
        [1.7316],
        [1.1398],
        [1.6763],
        [1.3494],
        [1.9143],
        [1.9605],
        [1.7231],
        [1.7139],
        [1.0791],
        [2.4554],
        [2.1223],
        [1.8507],
        [2.3722],
        [2.4520],
        [2.0790],
        [2.8662],
        [0.9427],
        [1.4325],
        [2.2808],
        [2.2619],
        [2.2977],
        [1.9784],
        [1.9076],
        [1.7932],
        [2.3818],
        [2.4369],
        [3.1063],
        [2.9670],
        [1.6706],
        [1.5717],
        [2.0293],
        [1.3217],
        [2.0487],
        [1.3000],
        [1.3755],
        [3

tensor([[1.4193],
        [2.1862],
        [2.1723],
        [1.2007],
        [1.2813],
        [3.7444],
        [2.2936],
        [1.7810],
        [1.3201],
        [1.7749],
        [1.9487],
        [2.6032],
        [2.6095],
        [1.8141],
        [1.2580],
        [1.1709],
        [0.9025],
        [1.6211],
        [1.4808],
        [0.8382],
        [1.3429],
        [3.4770],
        [1.5266],
        [2.7871],
        [1.1539],
        [1.8141],
        [1.9017],
        [1.1521],
        [2.1168],
        [1.5971],
        [1.4144],
        [3.8995],
        [2.5878],
        [1.3195],
        [1.5865],
        [2.1081],
        [1.6690],
        [3.1650],
        [1.9546],
        [2.2156],
        [2.5696],
        [1.5175],
        [1.7027],
        [2.7374],
        [1.9676],
        [1.7974],
        [2.0288],
        [2.7458],
        [1.3046],
        [1.9016],
        [2.0419],
        [2.0089],
        [2.1155],
        [1.1727],
        [2.6909],
        [2

tensor([[1.7785],
        [1.5349],
        [1.5598],
        [0.8425],
        [1.4997],
        [1.5592],
        [1.4393],
        [3.1146],
        [3.3033],
        [1.7058],
        [1.4045],
        [1.9564],
        [3.1124],
        [1.1960],
        [1.7987],
        [1.2399],
        [2.2239],
        [3.0854],
        [2.4672],
        [2.1809],
        [2.7045],
        [2.1971],
        [2.2129],
        [1.7909],
        [1.6771],
        [1.6464],
        [1.2058],
        [1.7833],
        [1.2086],
        [2.2043],
        [4.0955],
        [1.6370],
        [1.6237],
        [1.8923],
        [1.3973],
        [1.8433],
        [2.3840],
        [1.8967],
        [1.3827],
        [1.0104],
        [2.8857],
        [1.3952],
        [2.1152],
        [1.7566],
        [2.1422],
        [1.1952],
        [2.2964],
        [0.7784],
        [2.6945],
        [1.7374],
        [0.8938],
        [2.8097],
        [1.8927],
        [1.2109],
        [1.2500],
        [1

tensor([[1.2256],
        [2.6488],
        [1.9439],
        [2.0130],
        [1.3790],
        [1.3242],
        [2.3787],
        [1.0645],
        [1.8871],
        [2.4827],
        [1.3817],
        [1.2655],
        [1.0497],
        [1.2570],
        [3.5795],
        [2.0952],
        [2.1734],
        [2.6731],
        [2.7392],
        [0.9556],
        [2.2657],
        [1.4276],
        [2.5609],
        [1.3891],
        [2.0457],
        [1.9776],
        [0.7237],
        [1.5685],
        [1.2971],
        [2.4185],
        [2.4003],
        [2.3156],
        [2.5615],
        [2.1326],
        [2.8726],
        [2.8937],
        [2.5858],
        [1.8503],
        [1.3473],
        [2.8372],
        [2.4380],
        [2.4228],
        [2.6692],
        [1.5626],
        [3.3720],
        [1.7125],
        [1.6550],
        [3.7448],
        [1.2451],
        [3.2897],
        [1.8145],
        [1.4682],
        [0.8548],
        [3.0612],
        [2.1344],
        [2

tensor([[1.2743],
        [2.6055],
        [1.8206],
        [1.5913],
        [1.5872],
        [0.4984],
        [1.8133],
        [2.3112],
        [2.1204],
        [2.2036],
        [3.0676],
        [2.1718],
        [2.3784],
        [1.0793],
        [2.2047],
        [1.2397],
        [1.2588],
        [2.6926],
        [2.0204],
        [3.1482],
        [1.9724],
        [2.7948],
        [1.7721],
        [1.8500],
        [1.4708],
        [1.6767],
        [2.0689],
        [1.4653],
        [1.9506],
        [1.3764],
        [1.7778],
        [1.8115],
        [1.9804],
        [1.8485],
        [1.5777],
        [0.9030],
        [1.5530],
        [1.5352],
        [1.6433],
        [2.5339],
        [2.0232],
        [1.0238],
        [1.6701],
        [2.7546],
        [1.0113],
        [1.9885],
        [2.3406],
        [2.7393],
        [1.5488],
        [2.2313],
        [2.3654],
        [1.2506],
        [1.6791],
        [1.2596],
        [2.1575],
        [2

tensor([[2.1017],
        [2.7749],
        [2.0017],
        [1.4521],
        [1.6690],
        [1.9752],
        [1.6932],
        [1.1808],
        [1.7422],
        [1.9497],
        [2.2736],
        [2.3635],
        [1.6402],
        [2.3628],
        [1.4602],
        [1.3906],
        [1.7491],
        [2.3618],
        [1.8678],
        [2.1395],
        [3.3932],
        [1.5038],
        [1.1935],
        [1.8353],
        [1.5743],
        [1.2849],
        [2.1129],
        [3.3346],
        [1.4836],
        [2.0415],
        [1.1206],
        [1.7582],
        [2.2549],
        [0.9682],
        [2.0304],
        [1.5915],
        [1.4458],
        [2.1945],
        [3.3231],
        [2.9670],
        [1.5496],
        [0.8814],
        [1.6973],
        [1.9547],
        [3.5281],
        [1.2930],
        [1.9013],
        [1.9660],
        [2.6145],
        [0.8322],
        [2.1675],
        [1.7984],
        [1.6631],
        [1.0844],
        [1.3534],
        [2

tensor([[2.8328],
        [1.8566],
        [1.1330],
        [2.2250],
        [1.4025],
        [1.4843],
        [2.0554],
        [1.6041],
        [3.8062],
        [1.3053],
        [1.6513],
        [2.0978],
        [1.5018],
        [2.8679],
        [3.0349],
        [1.4138],
        [3.2469],
        [2.4823],
        [2.3018],
        [1.3081],
        [2.3702],
        [1.4563],
        [0.9996],
        [1.2961],
        [2.4700],
        [2.4274],
        [2.8267],
        [0.8433],
        [0.6966],
        [1.6047],
        [1.7585],
        [1.2953],
        [3.1403],
        [0.6026],
        [0.8446],
        [3.8716],
        [2.9051],
        [1.5778],
        [1.8309],
        [1.5526],
        [1.7387],
        [1.7094],
        [1.5788],
        [1.8142],
        [2.2039],
        [1.1618],
        [2.8407],
        [1.4967],
        [1.7409],
        [1.6000],
        [1.2116],
        [0.9229],
        [0.6542],
        [2.5060],
        [3.5632],
        [2

tensor([[2.4377],
        [2.5564],
        [1.7055],
        [2.3916],
        [1.7948],
        [0.7492],
        [1.3317],
        [1.6791],
        [2.9691],
        [1.9265],
        [2.0533],
        [1.3435],
        [1.7525],
        [1.0287],
        [0.7140],
        [2.6590],
        [1.7769],
        [0.9238],
        [1.5647],
        [2.2136],
        [1.1998],
        [2.8687],
        [2.5684],
        [1.3309],
        [0.6972],
        [1.7967],
        [1.8698],
        [1.3752],
        [2.1977],
        [1.0404],
        [2.9534],
        [1.2001],
        [1.1486],
        [1.8925],
        [1.7679],
        [2.4410],
        [1.7214],
        [1.9672],
        [1.9050],
        [2.5993],
        [2.9590],
        [3.4317],
        [1.0890],
        [1.3602],
        [1.7952],
        [2.3638],
        [1.9837],
        [1.7448],
        [1.9662],
        [1.2980],
        [2.2056],
        [2.8361],
        [1.0990],
        [1.3548],
        [2.6596],
        [1

tensor([[1.0754],
        [0.7754],
        [1.4951],
        [2.3397],
        [1.6973],
        [0.9587],
        [2.5792],
        [1.8542],
        [2.1329],
        [1.7912],
        [2.8468],
        [1.7775],
        [2.1415],
        [1.9207],
        [1.7482],
        [1.1616],
        [1.0035],
        [1.9896],
        [2.2070],
        [0.4301],
        [0.8947],
        [3.3634],
        [1.8007],
        [1.6156],
        [2.3723],
        [1.4770],
        [2.3008],
        [1.4286],
        [2.1490],
        [2.2973],
        [2.0458],
        [1.7461],
        [1.6066],
        [1.8608],
        [2.4073],
        [2.9044],
        [1.7573],
        [1.6959],
        [2.1165],
        [2.2122],
        [1.0343],
        [0.9986],
        [0.9190],
        [1.3092],
        [1.4903],
        [2.9539],
        [1.3355],
        [1.8747],
        [1.8132],
        [1.7166],
        [2.8338],
        [1.1756],
        [2.1269],
        [1.2631],
        [1.6506],
        [0

tensor([[3.5353],
        [1.2630],
        [1.5226],
        [1.7747],
        [1.2291],
        [0.9910],
        [1.0444],
        [1.2345],
        [2.8241],
        [1.2755],
        [4.3839],
        [2.3322],
        [1.2208],
        [1.5587],
        [2.0074],
        [1.8472],
        [3.2383],
        [2.1062],
        [1.1455],
        [2.9482],
        [1.7622],
        [0.8726],
        [1.0349],
        [1.3443],
        [1.1480],
        [1.5730],
        [1.7698],
        [1.3358],
        [1.9877],
        [2.0691],
        [2.5677],
        [1.4908],
        [2.3086],
        [0.9275],
        [0.8221],
        [2.5425],
        [1.3427],
        [1.1088],
        [1.9431],
        [1.5707],
        [0.8754],
        [2.2968],
        [2.8260],
        [2.5626],
        [1.7491],
        [1.5430],
        [1.8935],
        [1.3454],
        [1.8894],
        [0.8495],
        [1.6696],
        [1.8033],
        [1.9199],
        [1.5880],
        [0.7877],
        [1

tensor([[1.5733],
        [2.3796],
        [2.2997],
        [0.8631],
        [2.1599],
        [2.7011],
        [1.9742],
        [1.4995],
        [3.3708],
        [1.1573],
        [3.2512],
        [1.2414],
        [1.3487],
        [0.7667],
        [2.0089],
        [1.6533],
        [1.5570],
        [2.2817],
        [0.7284],
        [1.6736],
        [1.6969],
        [1.8884],
        [1.2892],
        [2.0760],
        [2.3246],
        [1.6741],
        [2.5998],
        [1.3775],
        [1.8622],
        [1.7952],
        [2.0663],
        [1.8968],
        [2.8470],
        [1.7340],
        [0.3458],
        [2.3222],
        [0.6640],
        [0.5938],
        [2.0753],
        [1.8157],
        [0.8336],
        [3.1915],
        [1.9649],
        [1.7601],
        [1.3182],
        [2.3436],
        [0.6270],
        [1.8778],
        [1.9254],
        [2.8605],
        [0.9948],
        [2.5353],
        [0.8334],
        [1.6792],
        [0.9589],
        [2

tensor([[0.8827],
        [1.5214],
        [2.4549],
        [1.0072],
        [2.9636],
        [2.2414],
        [1.8862],
        [1.7744],
        [2.5613],
        [0.7921],
        [2.9309],
        [2.6044],
        [1.9117],
        [1.6608],
        [1.4703],
        [2.5580],
        [1.5264],
        [1.8964],
        [1.6882],
        [1.6060],
        [2.5353],
        [1.3062],
        [1.3188],
        [1.7922],
        [1.4617],
        [0.9349],
        [1.2831],
        [1.8715],
        [2.9249],
        [1.0931],
        [1.8030],
        [1.5919],
        [1.3670],
        [1.9003],
        [1.0922],
        [2.0546],
        [2.2726],
        [3.5653],
        [2.6135],
        [1.5117],
        [2.9215],
        [1.3758],
        [2.2118],
        [2.7831],
        [2.9759],
        [2.0595],
        [2.4694],
        [1.6612],
        [2.0485],
        [1.2613],
        [2.8475],
        [1.6741],
        [2.7799],
        [1.8162],
        [1.3506],
        [1

tensor([[1.3467],
        [1.3439],
        [2.7056],
        [1.3667],
        [2.4819],
        [1.7298],
        [1.2454],
        [1.2918],
        [1.3259],
        [1.2732],
        [1.5549],
        [1.9855],
        [1.2547],
        [1.8471],
        [1.6009],
        [1.7964],
        [2.8713],
        [0.8892],
        [1.3490],
        [2.7034],
        [1.3034],
        [1.2058],
        [1.9371],
        [1.4150],
        [2.3829],
        [0.8437],
        [1.8430],
        [2.8581],
        [1.7540],
        [2.2430],
        [1.4085],
        [1.7968],
        [1.2914],
        [1.8335],
        [2.5044],
        [2.2304],
        [1.2042],
        [2.4780],
        [1.9772],
        [1.4186],
        [1.1798],
        [1.7753],
        [1.1594],
        [2.9648],
        [2.9331],
        [2.7456],
        [2.4965],
        [2.2101],
        [2.0239],
        [2.7566],
        [1.2526],
        [1.7671],
        [3.0798],
        [2.4332],
        [1.8940],
        [1

tensor([[0.5604],
        [0.7578],
        [2.2864],
        [1.7335],
        [1.3287],
        [2.5116],
        [1.6677],
        [1.4754],
        [1.0041],
        [1.6341],
        [1.7238],
        [1.0761],
        [2.1136],
        [1.8953],
        [1.8687],
        [2.4445],
        [2.6256],
        [1.2002],
        [1.8704],
        [1.9001],
        [1.7962],
        [2.2550],
        [1.0974],
        [2.1711],
        [2.1674],
        [1.6416],
        [2.1778],
        [1.0004],
        [0.7272],
        [1.4104],
        [0.8331],
        [1.6580],
        [1.5017],
        [2.4519],
        [1.3896],
        [2.7463],
        [1.7667],
        [2.4928],
        [1.5010],
        [1.4964],
        [1.4477],
        [1.3603],
        [1.3732],
        [1.8024],
        [2.0743],
        [1.7151],
        [1.2203],
        [1.4288],
        [2.5952],
        [2.7939],
        [0.9316],
        [1.2237],
        [1.5390],
        [1.3266],
        [2.1176],
        [1

tensor([[2.3316],
        [1.0120],
        [1.9741],
        [1.4323],
        [1.5689],
        [1.9556],
        [2.2054],
        [1.5193],
        [1.6282],
        [0.9910],
        [0.7151],
        [1.6918],
        [1.6225],
        [1.1833],
        [2.6236],
        [1.4844],
        [1.8222],
        [1.3251],
        [1.4932],
        [1.9638],
        [1.0912],
        [1.8166],
        [2.0018],
        [1.0305],
        [4.8577],
        [1.7307],
        [1.5083],
        [2.2854],
        [1.8000],
        [2.9992],
        [1.9391],
        [1.3698],
        [1.7420],
        [0.9564],
        [1.5756],
        [1.1605],
        [2.5932],
        [2.9951],
        [1.6121],
        [1.7155],
        [2.0060],
        [1.9582],
        [2.4423],
        [0.6643],
        [2.6644],
        [1.6957],
        [1.7340],
        [1.7791],
        [0.5982],
        [2.2734],
        [2.0676],
        [2.1880],
        [1.7919],
        [2.2023],
        [1.3592],
        [1

tensor([[1.5668],
        [1.0271],
        [1.7907],
        [1.0535],
        [1.8505],
        [1.7838],
        [2.0530],
        [3.1777],
        [2.0231],
        [1.7551],
        [0.7354],
        [0.9512],
        [2.8461],
        [1.5065],
        [1.2249],
        [1.9696],
        [1.4575],
        [1.4082],
        [1.0664],
        [1.6486],
        [2.1629],
        [2.1649],
        [1.1970],
        [1.0893],
        [1.7054],
        [2.2957],
        [1.2222],
        [1.0948],
        [1.0900],
        [1.3688],
        [0.8610],
        [1.6674],
        [2.2163],
        [2.2061],
        [2.5285],
        [1.4605],
        [1.7949],
        [0.8016],
        [1.7044],
        [2.0440],
        [0.7944],
        [1.1710],
        [1.4536],
        [2.5878],
        [2.2931],
        [1.6185],
        [1.1541],
        [1.5186],
        [1.2374],
        [1.5919],
        [1.4256],
        [2.3693],
        [2.3455],
        [1.2437],
        [1.4892],
        [1

        [1.5250]], grad_fn=<NegBackward>)
tensor([[1.6156],
        [1.4407],
        [1.1908],
        [1.4771],
        [1.7613],
        [3.4125],
        [1.5898],
        [1.7412],
        [1.3890],
        [1.8926],
        [1.7279],
        [1.8866],
        [0.8662],
        [1.9356],
        [1.6576],
        [1.2954],
        [1.7433],
        [2.1503],
        [2.3169],
        [1.2281],
        [1.2076],
        [1.2286],
        [1.2762],
        [2.0229],
        [1.2348],
        [1.2025],
        [1.2195],
        [1.2685],
        [1.5185],
        [1.3215],
        [1.8102],
        [1.1289],
        [3.5466],
        [0.7677],
        [1.4690],
        [1.7335],
        [2.5921],
        [1.1707],
        [2.0078],
        [1.7295],
        [0.6567],
        [1.0413],
        [3.1206],
        [1.8085],
        [1.7508],
        [1.7798],
        [1.6124],
        [1.0577],
        [1.8429],
        [1.4148],
        [1.8452],
        [1.7161],
        [1.6495],
    

tensor([[1.7194],
        [1.4426],
        [2.2533],
        [0.9556],
        [3.3132],
        [0.8024],
        [1.6452],
        [2.7996],
        [2.5389],
        [3.4248],
        [1.6866],
        [1.5977],
        [1.9653],
        [1.5729],
        [0.3156],
        [3.1667],
        [2.1294],
        [1.5327],
        [1.8068],
        [1.5589],
        [1.4177],
        [2.1625],
        [1.3549],
        [1.3394],
        [1.5526],
        [1.2470],
        [2.4066],
        [1.3550],
        [2.1539],
        [2.6550],
        [1.2076],
        [2.1531],
        [1.8188],
        [0.9960],
        [1.0251],
        [0.9413],
        [0.8466],
        [2.3807],
        [3.4720],
        [1.2757],
        [1.5821],
        [1.4777],
        [2.3665],
        [1.2414],
        [2.1515],
        [1.4308],
        [1.4427],
        [2.1302],
        [1.7212],
        [1.9596],
        [1.8591],
        [1.9433],
        [1.9430],
        [1.1561],
        [2.2320],
        [2

tensor([[1.8904],
        [1.7498],
        [1.6297],
        [1.1723],
        [3.1263],
        [1.3782],
        [1.8447],
        [1.1465],
        [1.9291],
        [1.4721],
        [1.0214],
        [1.5471],
        [1.9433],
        [2.6370],
        [0.2209],
        [1.5608],
        [2.7161],
        [2.4418],
        [1.8818],
        [1.9803],
        [0.9817],
        [2.0466],
        [1.5887],
        [1.7920],
        [2.8820],
        [1.7852],
        [2.3192],
        [0.7887],
        [2.7094],
        [2.4428],
        [2.3449],
        [0.7576],
        [1.9262],
        [1.3515],
        [1.6784],
        [1.5097],
        [1.7680],
        [0.8974],
        [1.4992],
        [1.2418],
        [1.8049],
        [1.6315],
        [0.8764],
        [1.4682],
        [2.6899],
        [1.4117],
        [1.9096],
        [3.1430],
        [0.9475],
        [1.2180],
        [2.4769],
        [2.0097],
        [3.4507],
        [1.0258],
        [1.4565],
        [1

tensor([[2.3304],
        [2.7604],
        [0.9401],
        [1.7549],
        [2.4279],
        [1.7941],
        [1.0859],
        [2.0524],
        [3.6404],
        [3.1521],
        [1.6200],
        [1.6548],
        [0.6571],
        [2.7656],
        [0.8924],
        [1.1114],
        [1.6981],
        [1.3062],
        [1.3964],
        [1.3238],
        [1.0803],
        [2.6228],
        [1.5121],
        [0.9219],
        [0.2110],
        [3.2463],
        [1.3961],
        [1.3642],
        [1.6248],
        [1.1643],
        [1.7399],
        [2.0765],
        [2.7761],
        [1.9864],
        [2.6083],
        [3.1671],
        [1.4315],
        [0.6950],
        [2.8657],
        [1.4051],
        [2.0974],
        [2.4005],
        [0.8631],
        [1.7097],
        [1.5778],
        [0.7368],
        [1.4316],
        [2.0439],
        [1.9445],
        [1.7641],
        [1.9941],
        [1.7618],
        [0.6038],
        [2.0585],
        [2.9844],
        [3

tensor([[0.9283],
        [1.9045],
        [0.9295],
        [1.0353],
        [1.8703],
        [1.2369],
        [2.1913],
        [2.1513],
        [1.3146],
        [1.1627],
        [1.3034],
        [2.0455],
        [1.4059],
        [1.7888],
        [1.4955],
        [1.7196],
        [2.4571],
        [1.3988],
        [1.2930],
        [1.9813],
        [2.8662],
        [1.4207],
        [0.4567],
        [2.8145],
        [1.3817],
        [1.8791],
        [3.0744],
        [1.5237],
        [1.6832],
        [1.1174],
        [0.8024],
        [1.1619],
        [0.9414],
        [1.0537],
        [2.2084],
        [1.4302],
        [1.7840],
        [1.0374],
        [2.2940],
        [2.2758],
        [1.8455],
        [2.6336],
        [1.9842],
        [0.8021],
        [1.1929],
        [1.1573],
        [0.9145],
        [1.9234],
        [1.1217],
        [1.9919],
        [1.3747],
        [2.7040],
        [1.9024],
        [2.2571],
        [1.4731],
        [2

tensor([[1.1756],
        [1.1820],
        [1.6299],
        [0.8532],
        [0.8720],
        [0.7019],
        [1.7120],
        [1.2385],
        [1.4657],
        [1.7643],
        [0.7983],
        [2.0736],
        [0.3071],
        [1.6564],
        [0.5303],
        [1.7318],
        [1.2364],
        [0.9261],
        [1.1802],
        [1.5626],
        [1.6743],
        [1.2438],
        [1.7566],
        [0.9987],
        [1.8508],
        [1.1544],
        [2.3884],
        [1.7986],
        [1.5544],
        [1.3462],
        [0.5005],
        [1.1493],
        [1.3690],
        [1.1019],
        [1.6629],
        [1.4582],
        [0.6262],
        [1.5839],
        [0.8294],
        [1.9662],
        [2.6499],
        [0.9639],
        [3.1084],
        [2.5050],
        [1.5526],
        [0.8075],
        [2.7200],
        [1.6530],
        [2.0281],
        [1.2315],
        [1.6754],
        [0.6668],
        [1.7662],
        [1.2571],
        [0.3537],
        [2

tensor([[2.0191],
        [1.4348],
        [2.3237],
        [1.2068],
        [1.9467],
        [2.5435],
        [1.3600],
        [2.0909],
        [2.0030],
        [0.7516],
        [2.9640],
        [1.9192],
        [1.9211],
        [0.9994],
        [2.5994],
        [2.2096],
        [2.3370],
        [0.8709],
        [1.0057],
        [1.1719],
        [1.7990],
        [1.6039],
        [2.1839],
        [1.1412],
        [1.8115],
        [1.4859],
        [1.8049],
        [2.0474],
        [1.3216],
        [1.3158],
        [0.9011],
        [1.2591],
        [1.3370],
        [1.1722],
        [2.1822],
        [1.2433],
        [1.2201],
        [2.4575],
        [0.5958],
        [2.4978],
        [2.7351],
        [0.9938],
        [2.4872],
        [1.1817],
        [1.0762],
        [0.8431],
        [1.5008],
        [1.2272],
        [1.5519],
        [1.2506],
        [1.9250],
        [1.5359],
        [2.0598],
        [2.0790],
        [2.3446],
        [1

tensor([[1.3789],
        [2.0491],
        [1.2596],
        [1.9492],
        [1.0552],
        [1.7588],
        [1.2082],
        [0.8609],
        [1.1751],
        [0.2584],
        [1.0079],
        [2.1632],
        [1.5672],
        [1.7589],
        [2.1247],
        [1.4075],
        [3.0198],
        [0.9689],
        [2.1817],
        [2.0422],
        [2.0403],
        [3.3501],
        [1.1633],
        [1.1982],
        [1.5215],
        [1.3326],
        [2.7582],
        [2.7239],
        [2.0412],
        [2.0597],
        [0.5707],
        [1.3758],
        [1.6164],
        [0.7929],
        [1.7568],
        [1.3726],
        [1.5498],
        [0.6145],
        [1.0468],
        [0.6283],
        [1.8405],
        [0.7755],
        [1.3177],
        [2.2812],
        [1.6506],
        [1.1872],
        [2.3683],
        [2.4392],
        [2.6369],
        [2.1007],
        [1.9208],
        [2.4397],
        [2.7388],
        [0.8041],
        [1.2862],
        [2

tensor([[1.9645],
        [0.9316],
        [0.9146],
        [0.3623],
        [1.3940],
        [1.7565],
        [2.3950],
        [0.9490],
        [0.6566],
        [1.9698],
        [1.3395],
        [1.3735],
        [3.5298],
        [1.5199],
        [1.0523],
        [0.6811],
        [1.5468],
        [2.6520],
        [2.8192],
        [1.9382],
        [0.8993],
        [1.0969],
        [2.9406],
        [1.1552],
        [3.0245],
        [1.8248],
        [0.8601],
        [0.8199],
        [1.7944],
        [1.4910],
        [0.8269],
        [0.6709],
        [2.0954],
        [0.4242],
        [2.0434],
        [0.2242],
        [0.3348],
        [0.5673],
        [1.3387],
        [1.3529],
        [2.0657],
        [1.4277],
        [2.2895],
        [2.0256],
        [1.4458],
        [1.8967],
        [0.8060],
        [2.1200],
        [2.0237],
        [3.1991],
        [1.9758],
        [0.8887],
        [1.6896],
        [2.4428],
        [1.1907],
        [1

tensor([[1.0311],
        [1.5308],
        [2.6575],
        [1.2849],
        [2.0308],
        [1.4424],
        [1.7195],
        [1.6762],
        [1.6845],
        [2.4845],
        [1.6473],
        [2.1760],
        [0.7967],
        [2.9325],
        [0.6251],
        [1.8981],
        [0.8991],
        [1.0410],
        [0.9380],
        [1.6306],
        [0.7940],
        [1.3742],
        [1.7145],
        [1.6183],
        [1.7693],
        [1.8526],
        [1.1368],
        [1.5217],
        [1.8928],
        [2.0389],
        [1.8238],
        [2.4579],
        [2.5340],
        [2.2048],
        [1.8029],
        [1.4782],
        [2.1736],
        [1.7727],
        [1.1607],
        [3.3373],
        [1.9866],
        [1.7224],
        [2.3283],
        [2.2684],
        [1.6935],
        [1.0967],
        [1.3025],
        [1.3703],
        [1.5360],
        [1.5059],
        [2.8893],
        [2.0240],
        [0.8167],
        [1.0283],
        [1.8552],
        [0

tensor([[1.5291],
        [2.2030],
        [1.6877],
        [2.3276],
        [1.4340],
        [2.9072],
        [2.5659],
        [2.7019],
        [1.4737],
        [1.9850],
        [1.1025],
        [1.0173],
        [2.5812],
        [0.9019],
        [1.8330],
        [2.0518],
        [1.7454],
        [1.5459],
        [1.3184],
        [2.0505],
        [1.8988],
        [1.0898],
        [1.5006],
        [1.1044],
        [2.5045],
        [2.2271],
        [1.4662],
        [1.2507],
        [0.7922],
        [1.9814],
        [2.0098],
        [1.4503],
        [1.8722],
        [1.5177],
        [1.5271],
        [1.0403],
        [1.9476],
        [1.9936],
        [1.9573],
        [1.9681],
        [2.1932],
        [2.5996],
        [1.5157],
        [2.5378],
        [2.0745],
        [1.7394],
        [1.8609],
        [1.4723],
        [1.0010],
        [0.9849],
        [1.9553],
        [1.0285],
        [1.6804],
        [1.4470],
        [2.9961],
        [1

tensor([[1.0143],
        [0.8998],
        [0.9985],
        [1.5281],
        [0.4509],
        [1.2161],
        [1.9111],
        [1.4435],
        [1.4426],
        [1.5471],
        [2.4409],
        [1.2655],
        [2.6192],
        [2.7708],
        [1.5410],
        [1.4375],
        [1.5689],
        [1.2526],
        [2.4399],
        [1.8188],
        [1.4393],
        [1.1200],
        [2.7334],
        [2.2690],
        [1.7094],
        [2.0368],
        [0.9978],
        [1.5585],
        [2.2413],
        [2.2566],
        [2.5615],
        [1.9642],
        [1.4378],
        [2.1619],
        [1.6154],
        [2.0504],
        [1.7996],
        [1.5659],
        [1.4271],
        [1.3304],
        [2.1149],
        [1.8676],
        [1.2482],
        [0.7194],
        [2.1206],
        [2.5508],
        [1.3891],
        [1.5488],
        [1.6730],
        [1.4177],
        [1.7746],
        [0.6675],
        [2.3381],
        [1.4252],
        [1.5569],
        [1

tensor([[0.6426],
        [0.8765],
        [0.7825],
        [0.3326],
        [1.4859],
        [2.2373],
        [1.2803],
        [1.4830],
        [1.6119],
        [1.6708],
        [0.7991],
        [2.3912],
        [1.7845],
        [1.7181],
        [1.7072],
        [1.1528],
        [1.0450],
        [1.3114],
        [1.9762],
        [1.0607],
        [4.2242],
        [1.2911],
        [0.3645],
        [2.1596],
        [1.4639],
        [3.0402],
        [1.2856],
        [0.5368],
        [1.1695],
        [0.7697],
        [2.5271],
        [1.0243],
        [0.9137],
        [2.4572],
        [1.0439],
        [0.8298],
        [1.0376],
        [2.0411],
        [2.3188],
        [1.2957],
        [1.5565],
        [2.0482],
        [2.7455],
        [1.6190],
        [1.8561],
        [1.3319],
        [0.9433],
        [1.0856],
        [2.7897],
        [0.8479],
        [0.6557],
        [1.9273],
        [2.5417],
        [1.6180],
        [0.9557],
        [1

tensor([[2.1232],
        [2.0561],
        [1.0906],
        [1.6066],
        [1.7408],
        [1.1600],
        [0.4028],
        [0.5181],
        [1.3412],
        [1.5853],
        [3.5591],
        [1.1054],
        [1.9860],
        [2.4714],
        [0.9083],
        [1.9262],
        [2.0134],
        [1.9656],
        [2.0782],
        [1.7060],
        [0.5875],
        [2.3625],
        [2.3431],
        [1.6675],
        [0.8227],
        [1.5488],
        [0.5435],
        [1.1395],
        [2.3500],
        [0.9983],
        [1.4878],
        [2.5448],
        [0.9732],
        [1.8138],
        [1.0028],
        [2.4812],
        [2.1602],
        [1.2468],
        [2.1377],
        [2.2469],
        [2.3222],
        [2.0738],
        [2.1984],
        [1.6953],
        [1.1681],
        [2.3238],
        [1.3971],
        [1.4734],
        [2.7408],
        [1.2800],
        [1.4853],
        [0.7219],
        [1.0927],
        [0.8267],
        [0.7329],
        [1

tensor([[2.6276],
        [1.3705],
        [0.7692],
        [2.3223],
        [1.1391],
        [1.5365],
        [1.8160],
        [0.9077],
        [2.2476],
        [2.5483],
        [1.9367],
        [2.0612],
        [1.0537],
        [1.4308],
        [2.5730],
        [0.7124],
        [1.9743],
        [1.3502],
        [1.9897],
        [1.8618],
        [1.4953],
        [1.7483],
        [0.5371],
        [0.8114],
        [2.2976],
        [0.4872],
        [2.8173],
        [1.4312],
        [0.7443],
        [1.9704],
        [2.3899],
        [1.0212],
        [1.6546],
        [0.8675],
        [1.4405],
        [1.5695],
        [1.8544],
        [1.4565],
        [1.1333],
        [1.4027],
        [2.2599],
        [0.6835],
        [2.2945],
        [0.5378],
        [2.2496],
        [1.9872],
        [2.0046],
        [1.1285],
        [1.0631],
        [1.5428],
        [0.5039],
        [2.6543],
        [1.7201],
        [1.0944],
        [0.7754],
        [2

tensor([[2.1427],
        [1.2488],
        [0.9532],
        [1.3235],
        [1.7281],
        [1.8382],
        [1.6417],
        [1.0337],
        [1.5554],
        [1.5274],
        [2.9109],
        [1.9939],
        [1.8291],
        [1.7245],
        [1.5071],
        [0.7352],
        [0.8992],
        [2.3396],
        [0.4550],
        [1.4837],
        [1.6912],
        [1.7254],
        [2.0067],
        [1.0420],
        [2.3253],
        [1.1173],
        [1.5643],
        [1.5908],
        [0.5417],
        [2.0437],
        [1.4236],
        [3.2833],
        [1.1537],
        [1.3310],
        [1.0124],
        [2.1802],
        [1.4747],
        [2.0104],
        [0.7231],
        [1.1825],
        [0.6046],
        [1.0343],
        [0.5874],
        [0.9815],
        [1.0314],
        [1.9968],
        [2.7396],
        [2.1372],
        [1.1498],
        [2.2247],
        [1.4819],
        [0.7036],
        [2.9382],
        [1.7019],
        [2.8861],
        [1

tensor([[2.3248],
        [1.9037],
        [2.3603],
        [1.8630],
        [1.7149],
        [0.5638],
        [1.5430],
        [1.7429],
        [1.4148],
        [0.3577],
        [0.9939],
        [0.7791],
        [1.9257],
        [1.8643],
        [0.3968],
        [1.4505],
        [1.5638],
        [1.4565],
        [1.2129],
        [1.8620],
        [1.0614],
        [2.1437],
        [2.0319],
        [2.5166],
        [0.9007],
        [1.8935],
        [1.7405],
        [2.3413],
        [1.3753],
        [1.3876],
        [1.5866],
        [1.3810],
        [1.1101],
        [1.8220],
        [0.5218],
        [1.9415],
        [1.5001],
        [2.0283],
        [0.5669],
        [0.5554],
        [1.6316],
        [2.2431],
        [2.1764],
        [1.9216],
        [1.4929],
        [1.0821],
        [1.9977],
        [1.6565],
        [1.5005],
        [2.1983],
        [0.5019],
        [1.2711],
        [2.1401],
        [2.1686],
        [0.4889],
        [2

tensor([[2.1689],
        [0.5689],
        [1.2194],
        [1.8019],
        [1.5176],
        [0.8623],
        [1.0532],
        [1.4853],
        [1.2164],
        [1.3034],
        [1.0286],
        [0.7773],
        [1.6743],
        [0.7701],
        [2.2488],
        [0.5992],
        [1.8549],
        [2.0252],
        [0.8448],
        [1.7640],
        [0.7295],
        [1.1194],
        [0.5689],
        [1.2179],
        [0.4373],
        [2.4294],
        [1.2241],
        [1.2689],
        [1.5401],
        [2.0351],
        [1.0717],
        [0.7654],
        [0.4061],
        [2.4269],
        [2.1334],
        [1.5336],
        [3.9029],
        [1.6670],
        [1.7560],
        [0.7335],
        [2.5495],
        [1.6578],
        [0.9706],
        [2.3157],
        [2.7607],
        [1.5344],
        [0.6708],
        [1.3805],
        [1.1871],
        [1.0221],
        [1.7738],
        [1.6119],
        [2.3310],
        [1.2427],
        [0.2390],
        [1

tensor([[1.0346],
        [1.0990],
        [1.4520],
        [0.9984],
        [0.7787],
        [1.6895],
        [2.0335],
        [0.9618],
        [0.3817],
        [0.9037],
        [2.0787],
        [0.8416],
        [2.0198],
        [0.8980],
        [0.6854],
        [1.3278],
        [2.0559],
        [1.1484],
        [1.0123],
        [1.8884],
        [0.6403],
        [0.7187],
        [1.8798],
        [1.0763],
        [1.2567],
        [1.8600],
        [1.0287],
        [1.9504],
        [1.5133],
        [2.7935],
        [1.2142],
        [1.1342],
        [0.3951],
        [1.1649],
        [1.5222],
        [1.5003],
        [2.0476],
        [0.9757],
        [2.9049],
        [0.7357],
        [0.4117],
        [1.1345],
        [0.9191],
        [1.0982],
        [0.5728],
        [1.6675],
        [2.0980],
        [0.9630],
        [1.6132],
        [1.9172],
        [4.1882],
        [2.3669],
        [2.5018],
        [1.1094],
        [0.5496],
        [2

tensor([[0.6416],
        [0.7148],
        [2.2616],
        [0.5866],
        [1.1646],
        [1.1279],
        [0.6344],
        [1.2744],
        [2.3412],
        [1.0080],
        [0.6096],
        [1.4455],
        [2.1961],
        [3.3248],
        [1.0836],
        [2.1807],
        [0.1404],
        [1.6913],
        [1.3414],
        [0.7804],
        [0.4678],
        [0.9609],
        [1.7253],
        [1.3914],
        [1.2865],
        [0.9966],
        [0.3863],
        [0.2859],
        [1.9086],
        [2.2524],
        [1.4285],
        [1.1367],
        [0.5170],
        [0.8785],
        [0.8980],
        [0.8318],
        [0.4419],
        [1.4029],
        [0.8093],
        [1.5959],
        [0.5134],
        [0.4735],
        [0.8942],
        [0.8441],
        [1.2229],
        [1.5543],
        [1.0940],
        [1.6974],
        [2.1371],
        [1.0616],
        [1.7023],
        [2.6182],
        [0.6142],
        [2.2414],
        [2.0105],
        [2

tensor([[2.1256],
        [1.1894],
        [2.2901],
        [0.8909],
        [1.1585],
        [1.5297],
        [2.4447],
        [0.9539],
        [1.3771],
        [2.1499],
        [1.6452],
        [2.0880],
        [1.0698],
        [2.0318],
        [1.9684],
        [1.9036],
        [0.9530],
        [1.6748],
        [2.7401],
        [3.1497],
        [0.8774],
        [1.4927],
        [1.2596],
        [1.1410],
        [1.5328],
        [0.6818],
        [1.2720],
        [2.9271],
        [1.2031],
        [1.7484],
        [1.0719],
        [1.0167],
        [1.5742],
        [1.2554],
        [1.7193],
        [1.6436],
        [1.5963],
        [0.4081],
        [2.7627],
        [0.9849],
        [2.1643],
        [2.1417],
        [1.6916],
        [1.9506],
        [1.3530],
        [1.1308],
        [1.3398],
        [1.8959],
        [1.9490],
        [1.1515],
        [1.2329],
        [1.5166],
        [0.3970],
        [2.3238],
        [0.4353],
        [1

tensor([[2.2141],
        [1.5894],
        [0.6292],
        [2.6561],
        [1.0191],
        [0.8157],
        [1.3543],
        [2.3441],
        [1.6058],
        [1.6964],
        [0.8082],
        [0.9559],
        [0.9272],
        [3.1765],
        [2.0353],
        [2.1551],
        [1.9986],
        [1.4717],
        [1.9919],
        [0.9793],
        [0.7101],
        [2.3734],
        [1.6164],
        [1.7495],
        [2.2718],
        [0.8254],
        [0.5622],
        [0.7122],
        [1.6997],
        [1.9818],
        [2.0453],
        [2.8161],
        [1.3063],
        [1.3748],
        [2.1222],
        [2.0626],
        [2.4931],
        [1.3086],
        [1.5414],
        [0.6421],
        [1.8655],
        [2.2817],
        [1.9661],
        [0.9862],
        [1.7914],
        [2.5342],
        [2.3971],
        [1.2533],
        [0.8708],
        [0.9673],
        [1.6807],
        [2.5803],
        [0.9881],
        [1.0442],
        [0.4791],
        [1

tensor([[1.4854],
        [1.5879],
        [2.0222],
        [1.6141],
        [1.8684],
        [0.9870],
        [2.0742],
        [1.2748],
        [2.2434],
        [2.2352],
        [1.9560],
        [1.2619],
        [1.7935],
        [0.8613],
        [1.5964],
        [2.7322],
        [1.1377],
        [1.7139],
        [0.7492],
        [2.3027],
        [1.6300],
        [0.3538],
        [1.0630],
        [1.9878],
        [1.5539],
        [1.8713],
        [1.4017],
        [0.9728],
        [2.4089],
        [1.0095],
        [1.8216],
        [1.2577],
        [2.0762],
        [1.1283],
        [1.3512],
        [1.3078],
        [0.8340],
        [0.8571],
        [2.3059],
        [1.0977],
        [0.5419],
        [0.8816],
        [1.2903],
        [1.0951],
        [2.4980],
        [1.3762],
        [2.6534],
        [1.9130],
        [1.0208],
        [1.7029],
        [1.7016],
        [3.5416],
        [0.7221],
        [1.0523],
        [1.3821],
        [1

tensor([[1.1630],
        [1.0013],
        [1.6961],
        [0.5269],
        [1.1434],
        [1.6480],
        [1.5779],
        [0.6825],
        [2.0011],
        [1.2579],
        [0.8638],
        [1.6313],
        [2.3972],
        [0.9893],
        [0.6004],
        [1.0015],
        [1.7973],
        [1.1047],
        [0.7637],
        [2.7884],
        [1.1048],
        [0.8821],
        [1.7277],
        [1.2886],
        [2.3534],
        [1.2496],
        [2.3069],
        [0.8473],
        [1.0436],
        [1.3382],
        [0.7660],
        [1.5300],
        [2.9603],
        [1.9773],
        [1.6348],
        [4.3152],
        [1.4154],
        [1.0261],
        [1.1193],
        [1.5108],
        [2.3913],
        [1.4847],
        [1.0406],
        [1.8051],
        [0.7856],
        [1.2615],
        [1.2337],
        [1.8122],
        [1.9877],
        [0.7610],
        [2.4765],
        [1.6709],
        [1.6391],
        [0.9867],
        [1.4851],
        [1

tensor([[1.9899],
        [2.0509],
        [0.9070],
        [2.6433],
        [1.1551],
        [1.5739],
        [1.1227],
        [2.3097],
        [0.8221],
        [2.8793],
        [0.6695],
        [1.6009],
        [1.9455],
        [0.7984],
        [1.3728],
        [1.6277],
        [1.2252],
        [0.4826],
        [2.0290],
        [1.5423],
        [1.8710],
        [0.8653],
        [1.2783],
        [1.8036],
        [1.1411],
        [1.4989],
        [0.9377],
        [0.6077],
        [2.5197],
        [1.5668],
        [0.6025],
        [0.4903],
        [0.6688],
        [1.3659],
        [0.5854],
        [1.3672],
        [1.4703],
        [0.7800],
        [2.0014],
        [3.2550],
        [2.5061],
        [1.6759],
        [1.1876],
        [2.0939],
        [1.3522],
        [1.5475],
        [1.4300],
        [1.6149],
        [1.6645],
        [1.1600],
        [1.1563],
        [1.6725],
        [1.4583],
        [0.7282],
        [2.3605],
        [1

tensor([[0.4924],
        [1.8844],
        [1.4749],
        [3.6095],
        [1.5628],
        [1.9713],
        [2.0426],
        [2.8395],
        [1.6449],
        [1.3736],
        [1.8047],
        [1.8955],
        [1.5671],
        [0.6475],
        [0.9740],
        [0.8954],
        [0.6597],
        [0.5529],
        [0.5884],
        [1.7368],
        [1.0638],
        [1.8753],
        [1.0884],
        [1.4880],
        [0.3743],
        [0.9654],
        [2.0759],
        [1.1474],
        [1.9795],
        [1.3312],
        [1.9992],
        [1.8129],
        [0.9328],
        [0.9830],
        [1.9026],
        [1.8485],
        [2.0624],
        [1.5264],
        [1.6846],
        [0.8139],
        [0.9677],
        [1.8090],
        [1.2039],
        [1.0507],
        [1.5520],
        [1.5145],
        [1.4200],
        [0.9707],
        [0.8048],
        [2.4545],
        [2.2550],
        [0.5050],
        [1.3515],
        [0.5220],
        [2.3481],
        [1

tensor([[2.2314],
        [1.3554],
        [2.6346],
        [3.0206],
        [1.2172],
        [1.4700],
        [1.1110],
        [1.1022],
        [1.6520],
        [2.8491],
        [1.6969],
        [0.9347],
        [2.0726],
        [0.6759],
        [1.0469],
        [1.7234],
        [1.5730],
        [0.7544],
        [0.8490],
        [1.5887],
        [1.2299],
        [0.9431],
        [0.6851],
        [1.3998],
        [1.2670],
        [0.8488],
        [1.1007],
        [1.9608],
        [0.4150],
        [0.9215],
        [0.8928],
        [0.9671],
        [2.4456],
        [0.7343],
        [0.9370],
        [2.9342],
        [1.7272],
        [1.0129],
        [0.5995],
        [1.0057],
        [2.2164],
        [0.9615],
        [1.0259],
        [1.6486],
        [2.0679],
        [2.0278],
        [1.5493],
        [0.3978],
        [0.5206],
        [1.7005],
        [1.3392],
        [1.1501],
        [2.2607],
        [1.7529],
        [2.2119],
        [0

tensor([[1.0394],
        [4.9745],
        [2.8548],
        [1.7101],
        [4.2656],
        [0.6401],
        [1.9007],
        [2.0948],
        [0.7516],
        [0.4964],
        [1.1508],
        [2.0721],
        [1.3944],
        [0.9655],
        [2.3555],
        [2.5068],
        [1.4968],
        [0.6715],
        [1.1885],
        [2.8355],
        [0.7976],
        [2.0918],
        [0.9381],
        [1.1603],
        [2.1568],
        [0.6890],
        [0.8042],
        [0.8335],
        [0.4991],
        [0.9036],
        [1.7489],
        [0.6920],
        [1.2190],
        [1.7699],
        [0.8144],
        [0.2957],
        [0.9234],
        [2.4869],
        [0.9091],
        [1.9023],
        [1.6183],
        [1.4235],
        [1.8453],
        [1.1274],
        [0.9071],
        [1.0318],
        [1.3392],
        [1.6470],
        [1.6313],
        [1.7468],
        [1.5049],
        [2.1328],
        [2.4508],
        [0.7166],
        [1.7368],
        [2

tensor([[0.6566],
        [1.0762],
        [1.0372],
        [2.2138],
        [1.2630],
        [1.1498],
        [1.3547],
        [0.9729],
        [0.6039],
        [1.1156],
        [1.3780],
        [0.2961],
        [1.1517],
        [0.9914],
        [2.3771],
        [1.7913],
        [0.9359],
        [1.3477],
        [1.2469],
        [1.1428],
        [0.6989],
        [2.0816],
        [1.5323],
        [1.7082],
        [2.4822],
        [0.1407],
        [1.6067],
        [2.1147],
        [2.9163],
        [0.6203],
        [1.7889],
        [1.7173],
        [0.5692],
        [0.9883],
        [2.6056],
        [2.1825],
        [0.6346],
        [1.3316],
        [0.6536],
        [2.0896],
        [2.6025],
        [0.9319],
        [0.9296],
        [1.2803],
        [2.3658],
        [1.9179],
        [3.6890],
        [0.6955],
        [1.1748],
        [1.6733],
        [2.2136],
        [0.8590],
        [1.6379],
        [1.2340],
        [0.9529],
        [2

tensor([[0.5153],
        [1.4885],
        [1.0964],
        [0.3392],
        [1.9389],
        [1.1008],
        [2.0519],
        [1.2686],
        [2.3768],
        [2.4337],
        [1.0038],
        [1.2334],
        [1.1049],
        [0.9666],
        [2.5482],
        [1.0343],
        [2.2349],
        [1.3054],
        [0.7456],
        [0.5003],
        [1.6483],
        [0.8366],
        [0.8436],
        [1.5330],
        [0.8549],
        [2.1685],
        [0.7198],
        [2.0037],
        [0.8822],
        [2.6561],
        [1.3395],
        [0.5589],
        [0.9797],
        [1.5580],
        [2.3436],
        [0.2396],
        [1.4477],
        [0.9078],
        [2.1515],
        [0.8480],
        [1.9849],
        [0.7633],
        [1.1335],
        [1.7535],
        [1.7062],
        [0.4685],
        [2.3026],
        [1.3136],
        [0.6324],
        [0.7040],
        [0.9477],
        [0.7374],
        [1.7076],
        [0.7285],
        [2.3377],
        [0

tensor([[2.5079],
        [1.2955],
        [1.7901],
        [1.0159],
        [1.5072],
        [2.2011],
        [0.7095],
        [1.1092],
        [0.8704],
        [1.5100],
        [2.0662],
        [1.8966],
        [1.1177],
        [0.8658],
        [0.8240],
        [1.5529],
        [0.8602],
        [0.8991],
        [1.0804],
        [2.2493],
        [2.2301],
        [0.5422],
        [2.2830],
        [1.1410],
        [1.1868],
        [1.3016],
        [0.8084],
        [1.2359],
        [1.8434],
        [2.0135],
        [1.0722],
        [0.8895],
        [0.7657],
        [2.0812],
        [2.2700],
        [1.4675],
        [1.5557],
        [2.1733],
        [0.7798],
        [0.6033],
        [0.9771],
        [0.7777],
        [2.2571],
        [0.4760],
        [2.1538],
        [2.0748],
        [1.0322],
        [0.8653],
        [2.3839],
        [1.4293],
        [1.0794],
        [1.1204],
        [0.6074],
        [1.6657],
        [1.7043],
        [1

NameError: name 'train' is not defined